import json
from pathlib import Path
from typing import List, Dict, Any
from config.settings import RAW_DATA_PATH
from src.discovery.scraper import parse_creator_profile

DEFAULT_DISCOVERED_DATA: List[Dict[str, Any]] = [
    {
        "name": "Maya Lin",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/mayaglows",
        "follower_count": 28400,
        "engagement_rate": 4.2,
        "category": "Fashion & Beauty",
        "content_themes": ["Glass Skin Routines", "Korean Skincare", "Morning GRWM"],
        "recent_post_summary": "Morning glass skin routine breaking down gentle hyaluronic acid layering and reef-safe SPF reviews.",
        "email": "partnerships.maya@gmail.com",
        "website": "https://mayaglows.com",
        "audience_age": "18-24 (48%), 25-34 (38%)",
        "audience_gender": "Female (82%)",
        "audience_geography": "United States (64%), Canada (18%)",
        "bio": "Minimalist skincare enthusiast | Barrier repair & glowing complexion daily ✨"
    },
    {
        "name": "Chloe Vance",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@chloevancebeauty",
        "follower_count": 45200,
        "engagement_rate": 5.8,
        "category": "Fashion & Beauty",
        "content_themes": ["Acne-Safe Makeup", "Drugstore Dupes", "Texture Inclusivity"],
        "recent_post_summary": "Top 5 drugstore pore-blurring primers tested over active hormonal breakouts with wear-tests throughout the day.",
        "email": "chloevance.mgmt@gmail.com",
        "website": "Not Found",
        "audience_age": "18-24 (55%), 25-34 (32%)",
        "audience_gender": "Female (86%)",
        "audience_geography": "United States (72%), UK (12%)",
        "bio": "Normalizing skin texture one GRWM at a time 🤍 UGC creator & clean makeup fan"
    },
    {
        "name": "Elena Rostova",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/elenarostovastyle",
        "follower_count": 62100,
        "engagement_rate": 3.7,
        "category": "Fashion & Beauty",
        "content_themes": ["Capsule Wardrobe", "Neutral Aesthetics", "Sustainable Chic"],
        "recent_post_summary": "10 classic spring transitional outfit combinations using only 6 core wardrobe essentials.",
        "email": "contact@elenastyle.co",
        "website": "https://elenastyle.co",
        "audience_age": "25-34 (62%), 35-44 (22%)",
        "audience_gender": "Female (79%)",
        "audience_geography": "United Kingdom (51%), United States (28%)",
        "bio": "Curating timeless European style & mindful wardrobe investments. London based."
    },
    {
        "name": "Priya Sharma",
        "platform": "YouTube",
        "profile_url": "https://youtube.com/@priyabeautylab",
        "follower_count": 34800,
        "engagement_rate": 4.9,
        "category": "Fashion & Beauty",
        "content_themes": ["Skincare Chemistry", "Hyperpigmentation Care", "Ingredient Deep Dives"],
        "recent_post_summary": "Comprehensive 12-minute breakdown on tranexamic acid vs vitamin C for dark spots and melanin-rich skin.",
        "email": "priya.collabs@outlook.com",
        "website": "Not Found",
        "audience_age": "22-35 (70%)",
        "audience_gender": "Female (84%)",
        "audience_geography": "United States (42%), India (35%), UK (11%)",
        "bio": "Cosmetic formulation student sharing evidence-based skincare advice & honest reviews."
    },
    {
        "name": "Sofia Alvarez",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/sofia.curates",
        "follower_count": 18900,
        "engagement_rate": 3.4,
        "category": "Fashion & Beauty",
        "content_themes": ["Clean Girl Aesthetic", "Dewy Makeup", "Everyday Handbag Essentials"],
        "recent_post_summary": "Quick 5-minute everyday dewy skin makeup routine for corporate girls on the go.",
        "email": "sofia.alvarez.pr@gmail.com",
        "website": "https://beacons.ai/sofiacurates",
        "audience_age": "20-30 (65%)",
        "audience_gender": "Female (88%)",
        "audience_geography": "United States (68%), Australia (14%)",
        "bio": "Easy beauty routines for busy mornings | Coffee lover | NYC"
    },
    {
        "name": "Liam Bennett",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@liamgroomed",
        "follower_count": 22400,
        "engagement_rate": 4.1,
        "category": "Fashion & Beauty",
        "content_themes": ["Men's Skincare", "Hair Styling", "Minimalist Grooming"],
        "recent_post_summary": "Beginner friendly 3-step evening routine for men tackling razor burns and dry winter patches.",
        "email": "liam@groomedcreators.io",
        "website": "Not Found",
        "audience_age": "18-29 (74%)",
        "audience_gender": "Male (65%), Female (35%)",
        "audience_geography": "United States (58%), Canada (22%)",
        "bio": "Elevating modern men's grooming routines without the fluff. Straightforward product tests."
    },
    {
        "name": "Hannah Brooks",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/hannahbstyle",
        "follower_count": 51300,
        "engagement_rate": 3.9,
        "category": "Fashion & Beauty",
        "content_themes": ["Thrift Flips", "Styling Hauls", "Vintage Fashion"],
        "recent_post_summary": "Thrifting oversized blazers and tailoring them into modern chic cropped sets with styling tips.",
        "email": "hannahbrooksmgmt@gmail.com",
        "website": "Not Found",
        "audience_age": "18-28 (72%)",
        "audience_gender": "Female (89%)",
        "audience_geography": "United States (77%), UK (11%)",
        "bio": "Second-hand fashion advocate & creative upcycler. Style on a realistic budget 🌿"
    },
    {
        "name": "Nadia Osei",
        "platform": "YouTube",
        "profile_url": "https://youtube.com/@nadiaskindiaries",
        "follower_count": 41200,
        "engagement_rate": 5.1,
        "category": "Fashion & Beauty",
        "content_themes": ["Melanin Rich Skincare", "Hydration Routines", "Sunscreen Reviews"],
        "recent_post_summary": "Testing 8 popular chemical and mineral sunscreens with zero white cast on dark skin tones.",
        "email": "contact.nadiaosei@gmail.com",
        "website": "https://nadiaosei.com",
        "audience_age": "20-34 (68%)",
        "audience_gender": "Female (91%)",
        "audience_geography": "United States (52%), UK (24%), Ghana (12%)",
        "bio": "Certified esthetician talking barrier restoration, SPF, and gentle glow skincare."
    },
    {
        "name": "Camila Torres",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/camilastyleinspo",
        "follower_count": 14200,
        "engagement_rate": 4.6,
        "category": "Fashion & Beauty",
        "content_themes": ["Petite Fashion", "Workwear Looks", "Neutral Staples"],
        "recent_post_summary": "How to style high-waisted wide-leg trousers if you are under 5 foot 3 inches without shortening your silhouette.",
        "email": "camila.partnerships@gmail.com",
        "website": "Not Found",
        "audience_age": "22-34 (63%)",
        "audience_gender": "Female (92%)",
        "audience_geography": "United States (60%), Mexico (20%)",
        "bio": "Petite styling tricks, corporate casual lookbooks, and confidence building outfits."
    },
    {
        "name": "Zoe Kravitz-Fox",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@zoeskinjournal",
        "follower_count": 89000,
        "engagement_rate": 3.2,
        "category": "Fashion & Beauty",
        "content_themes": ["Barrier Repair", "Sensory Skincare", "Night Routine"],
        "recent_post_summary": "My slugging routine when skin barrier is compromised after cold winter air and retinol flaking.",
        "email": "zoe@skinjournaltalent.com",
        "website": "https://skinjournal.co",
        "audience_age": "18-30 (69%)",
        "audience_gender": "Female (85%)",
        "audience_geography": "United States (65%), UK (18%)",
        "bio": "Sensitive & eczema prone skin journey | Ceramide obsessor | Clean beauty advocate"
    },
    {
        "name": "Ananya Sen",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/ananyamakeup_art",
        "follower_count": 76500,
        "engagement_rate": 2.8,
        "category": "Fashion & Beauty",
        "content_themes": ["Bridal Glam", "Color Correction", "Long-Wear Makeup"],
        "recent_post_summary": "Under-eye color correction masterclass using peach tones and lightweight hydrating concealer.",
        "email": "ananya.sen.mua@gmail.com",
        "website": "Not Found",
        "audience_age": "20-35 (73%)",
        "audience_gender": "Female (94%)",
        "audience_geography": "India (55%), United States (22%), UAE (12%)",
        "bio": "Professional Makeup Artist | Editorial & Bridal Glam | Transforming everyday beauty"
    },
    {
        "name": "Oliver King",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@oliverfits",
        "follower_count": 31500,
        "engagement_rate": 4.7,
        "category": "Fashion & Beauty",
        "content_themes": ["Streetwear", "Sneaker Styling", "Seasonal Color Palettes"],
        "recent_post_summary": "Pairing earth tone cargo pants with minimalist cream knitwear and retro running sneakers.",
        "email": "oliverfits.collab@gmail.com",
        "website": "Not Found",
        "audience_age": "16-26 (80%)",
        "audience_gender": "Male (72%), Female (28%)",
        "audience_geography": "United States (69%), Canada (15%)",
        "bio": "Daily outfit recipes & elevated street style. Let's make dressing well simple."
    },
    {
        "name": "Jessica Chen",
        "platform": "YouTube",
        "profile_url": "https://youtube.com/@jessicachenglow",
        "follower_count": 58400,
        "engagement_rate": 3.6,
        "category": "Fashion & Beauty",
        "content_themes": ["Glass Skin", "Double Cleansing", "Morning Skincare Routine"],
        "recent_post_summary": "Why double cleansing changed my stubborn clogged pores: oil cleansers vs micellar waters.",
        "email": "jessica@glowcreators.com",
        "website": "https://jessicaglow.com",
        "audience_age": "20-32 (68%)",
        "audience_gender": "Female (87%)",
        "audience_geography": "United States (50%), Canada (21%), Singapore (14%)",
        "bio": "Sharing realistic skincare habits and holy-grail beauty discoveries every Tuesday."
    },
    {
        "name": "Freja Lindqvist",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/frejalind_style",
        "follower_count": 27200,
        "engagement_rate": 4.4,
        "category": "Fashion & Beauty",
        "content_themes": ["Scandi Minimalism", "Monochrome Outfits", "Sustainable Fabrics"],
        "recent_post_summary": "The Scandinavian coat edit: styling long wool coats in oat, charcoal, and warm camel.",
        "email": "freja@lindqvistcreative.se",
        "website": "Not Found",
        "audience_age": "22-38 (75%)",
        "audience_gender": "Female (83%)",
        "audience_geography": "Sweden (40%), Germany (25%), United States (20%)",
        "bio": "Stockholm-based minimalist fashion. Neutral palettes, cozy wool, and clean aesthetics."
    },
    {
        "name": "Kiran Patel",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@kiranwellness",
        "follower_count": 19500,
        "engagement_rate": 5.2,
        "category": "Fashion & Beauty",
        "content_themes": ["Holistic Beauty", "Ayurvedic Hair Oiling", "Skin Nutrition"],
        "recent_post_summary": "Rosemary and amla oil blend for scalp stimulation: my 6-month hair thickness transformation.",
        "email": "kiranwellness@gmail.com",
        "website": "Not Found",
        "audience_age": "18-32 (77%)",
        "audience_gender": "Female (88%)",
        "audience_geography": "United States (56%), UK (23%)",
        "bio": "Modern Ayurveda, scalp health rituals, and botanical skin nourishment."
    },
    {
        "name": "Taylor Morgan",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/taylormorganglow",
        "follower_count": 8300,
        "engagement_rate": 6.1,
        "category": "Fashion & Beauty",
        "content_themes": ["Clean Beauty", "Cruelty-Free Skincare", "Tinted Moisturizers"],
        "recent_post_summary": "Top 3 clean tinted moisturizers that actually last through a full gym workout and humid afternoon.",
        "email": "taylor@taylormorganglow.com",
        "website": "https://taylormorganglow.com",
        "audience_age": "20-30 (64%)",
        "audience_gender": "Female (90%)",
        "audience_geography": "United States (82%)",
        "bio": "Non-toxic & leaping bunny certified beauty. Real unfiltered skin always."
    },
    {
        "name": "Amira Al-Mansoor",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/amira_modestlooks",
        "follower_count": 68400,
        "engagement_rate": 3.8,
        "category": "Fashion & Beauty",
        "content_themes": ["Modest Fashion", "Hijab Styling", "Silk Scarf Trends"],
        "recent_post_summary": "5 chic modest summer outfits that keep you cool without compromising elegance.",
        "email": "amira.collabs@outlook.com",
        "website": "Not Found",
        "audience_age": "18-30 (81%)",
        "audience_gender": "Female (96%)",
        "audience_geography": "UAE (38%), UK (26%), United States (20%)",
        "bio": "Modest fashion styling and contemporary beauty for the modern woman."
    },
    {
        "name": "Lucas Rossi",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@lucasrossistyle",
        "follower_count": 16800,
        "engagement_rate": 4.5,
        "category": "Fashion & Beauty",
        "content_themes": ["Men's Fragrance", "Italian Tailoring", "Collar Styling"],
        "recent_post_summary": "3 versatile niche fragrances every gentleman should own for spring date nights.",
        "email": "lucas@rossistyle.it",
        "website": "Not Found",
        "audience_age": "21-35 (71%)",
        "audience_gender": "Male (80%)",
        "audience_geography": "Italy (42%), United States (30%), UK (18%)",
        "bio": "Milanese style inspiration, tailoring notes, and signature fragrance reviews."
    },
    {
        "name": "Becca Davies",
        "platform": "YouTube",
        "profile_url": "https://youtube.com/@beccasglowroom",
        "follower_count": 49200,
        "engagement_rate": 3.5,
        "category": "Fashion & Beauty",
        "content_themes": ["Affordable Skincare", "Ceramide Creams", "Sensitive Skin"],
        "recent_post_summary": "Budget barrier creams ranked: from drugstore staples to Korean cult favorites.",
        "email": "becca@beccasglowroom.co.uk",
        "website": "https://beccasglowroom.co.uk",
        "audience_age": "24-40 (68%)",
        "audience_gender": "Female (86%)",
        "audience_geography": "United Kingdom (62%), United States (24%)",
        "bio": "Sensible skincare for real life budgets. No sponsorships without thorough 30-day testing."
    },
    {
        "name": "Clara Dupont",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/claradupont_paris",
        "follower_count": 92400,
        "engagement_rate": 2.9,
        "category": "Fashion & Beauty",
        "content_themes": ["French Girl Beauty", "Red Lip Classics", "Parisian Outfits"],
        "recent_post_summary": "The 3 rules of effortless Parisian morning beauty: tinted balm, fluffy brows, and natural messy hair.",
        "email": "clara.dupont.contact@gmail.com",
        "website": "Not Found",
        "audience_age": "20-35 (70%)",
        "audience_gender": "Female (87%)",
        "audience_geography": "France (45%), United States (30%), UK (15%)",
        "bio": "Parisienne sharing daily chic moments, French pharmacy cult products & coffee walks."
    },
    {
        "name": "Marcus Aurel",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/marcusaurel_barber",
        "follower_count": 24800,
        "engagement_rate": 4.0,
        "category": "Fashion & Beauty",
        "content_themes": ["Beard Care", "Fades & Texture", "Men's Skin Prep"],
        "recent_post_summary": "Pre-shave oil vs shaving butter: preventing ingrown hairs on coarse curls.",
        "email": "collab@marcusaurel.com",
        "website": "https://marcusaurel.com",
        "audience_age": "20-38 (76%)",
        "audience_gender": "Male (85%)",
        "audience_geography": "United States (80%)",
        "bio": "Master barber & men's grooming educator. Clean lines & healthy skin."
    },
    {
        "name": "Yuki Tanaka",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@yukiglowstokyo",
        "follower_count": 38100,
        "engagement_rate": 5.4,
        "category": "Fashion & Beauty",
        "content_themes": ["J-Beauty", "Hydrating Lotions", "SPF Wear-Tests"],
        "recent_post_summary": "Top Japanese hydrating essence waters compared side-by-side on moisture meter.",
        "email": "yuki.creativetokyo@gmail.com",
        "website": "Not Found",
        "audience_age": "18-28 (78%)",
        "audience_gender": "Female (84%)",
        "audience_geography": "Japan (30%), United States (45%), Australia (15%)",
        "bio": "Exploring Tokyo beauty counters and viral J-Beauty gems. Daily skincare tests."
    },
    {
        "name": "Destiny Brooks",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/curlsbydestiny",
        "follower_count": 54600,
        "engagement_rate": 4.3,
        "category": "Fashion & Beauty",
        "content_themes": ["Curly Hair Routines", "Diffuser Techniques", "Scalp Care"],
        "recent_post_summary": "Step by step wash day for 3C/4A curls using protein-free leave-in conditioners.",
        "email": "destiny@curlsbydestiny.com",
        "website": "https://curlsbydestiny.com",
        "audience_age": "18-34 (82%)",
        "audience_gender": "Female (94%)",
        "audience_geography": "United States (85%)",
        "bio": "Embracing natural crown textures. Wash-and-go tutorials, deep conditioning tips."
    },
    {
        "name": "Mia Lind",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/mialindbeauty",
        "follower_count": 11800,
        "engagement_rate": 4.8,
        "category": "Fashion & Beauty",
        "content_themes": ["Lip Oil Reviews", "Clean Glow", "Soft Glam"],
        "recent_post_summary": "Ranking every peptide lip treatment for stickiness, plumping, and all-night hydration.",
        "email": "Not Found",
        "website": "https://mialind.bio.link",
        "audience_age": "18-26 (79%)",
        "audience_gender": "Female (91%)",
        "audience_geography": "United States (70%), Canada (18%)",
        "bio": "Everyday glow, peptide balms, and honest first impressions. DM for quick questions!"
    },
    {
        "name": "Tariq Edwards",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@tariqfits",
        "follower_count": 33900,
        "engagement_rate": 3.8,
        "category": "Fashion & Beauty",
        "content_themes": ["Minimalist Streetwear", "Jewelry Styling", "Outerwear"],
        "recent_post_summary": "How simple silver jewelry and clean watch straps instantly elevate a basic white tee outfit.",
        "email": "tariq.mgmt@gmail.com",
        "website": "Not Found",
        "audience_age": "18-27 (82%)",
        "audience_gender": "Male (70%)",
        "audience_geography": "United States (68%), UK (18%)",
        "bio": "Focusing on proportions, textures, and details. Everyday outfit inspo."
    },
    {
        "name": "Sienna Miller-Reid",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/siennabeautyedit",
        "follower_count": 47600,
        "engagement_rate": 3.3,
        "category": "Fashion & Beauty",
        "content_themes": ["Retinol Journey", "Mature Skin Care", "Glow Drops"],
        "recent_post_summary": "Over 35 skincare routine: smoothing fine lines without triggering rosacea flare-ups.",
        "email": "sienna.edit@gmail.com",
        "website": "Not Found",
        "audience_age": "28-45 (76%)",
        "audience_gender": "Female (90%)",
        "audience_geography": "United States (60%), UK (25%)",
        "bio": "Pro-aging gracefully ✨ Dermatologist-approved skincare for 30s & beyond."
    },
    {
        "name": "Leila Kassam",
        "platform": "YouTube",
        "profile_url": "https://youtube.com/@leilaskinstories",
        "follower_count": 21700,
        "engagement_rate": 5.0,
        "category": "Fashion & Beauty",
        "content_themes": ["Acne Healing", "Skin Positivity", "Gentle Cleansers"],
        "recent_post_summary": "Why I stopped using harsh foaming cleansers and how it reduced my cystic acne.",
        "email": "leilakassam.collab@gmail.com",
        "website": "Not Found",
        "audience_age": "18-28 (73%)",
        "audience_gender": "Female (88%)",
        "audience_geography": "Canada (42%), United States (40%)",
        "bio": "Normalizing adult acne and building a resilient, happy skin barrier."
    },
    {
        "name": "Noah Sterling",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@noahsterlingskin",
        "follower_count": 67300,
        "engagement_rate": 3.1,
        "category": "Fashion & Beauty",
        "content_themes": ["Sunscreen Demos", "Niacinamide", "Men's Skin Routine"],
        "recent_post_summary": "Applying 2 finger lengths of SPF on camera with UV mirror to check full coverage.",
        "email": "noahsterling.collabs@gmail.com",
        "website": "Not Found",
        "audience_age": "18-29 (70%)",
        "audience_gender": "Male (55%), Female (45%)",
        "audience_geography": "United States (75%)",
        "bio": "Sunscreen advocate & UV camera reviews. Keep your skin protected!"
    },
    {
        "name": "Aria Montgomery",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/ariamontgstyle",
        "follower_count": 29800,
        "engagement_rate": 4.1,
        "category": "Fashion & Beauty",
        "content_themes": ["Workwear Chic", "Blazer Outfits", "Monochrome Styling"],
        "recent_post_summary": "Transitioning tailored wide-leg trousers from morning meetings to evening dinners.",
        "email": "aria@montgomerystyle.com",
        "website": "https://ariamontgomerystyle.com",
        "audience_age": "24-38 (71%)",
        "audience_gender": "Female (86%)",
        "audience_geography": "United States (73%), Canada (15%)",
        "bio": "Elevated modern workwear and capsule styling for corporate professionals."
    },
    {
        "name": "Zara Vance",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@zaraglows",
        "follower_count": 15400,
        "engagement_rate": 5.9,
        "category": "Fashion & Beauty",
        "content_themes": ["Lip Combos", "Blush Hacks", "No-Foundation Makeup"],
        "recent_post_summary": "Creating a dewy cheek flush using cream blush and a hydrating peptide mist.",
        "email": "Not Found",
        "website": "https://snipfeed.co/zaraglows",
        "audience_age": "16-24 (85%)",
        "audience_gender": "Female (93%)",
        "audience_geography": "United States (78%)",
        "bio": "Obsessed with creamy textures & brown-girl lip combos. DM or follow for daily looks!"
    },
    {
        "name": "Danielle Green",
        "platform": "YouTube",
        "profile_url": "https://youtube.com/@daniellegreenhair",
        "follower_count": 73200,
        "engagement_rate": 3.7,
        "category": "Fashion & Beauty",
        "content_themes": ["Hair Oil Massages", "Bond Repair", "Heatless Curls"],
        "recent_post_summary": "Heatless robe belt curls test on waist-length fine hair: does it hold for 24 hours?",
        "email": "danielle@daniellegreenhair.com",
        "website": "https://daniellegreenhair.com",
        "audience_age": "20-35 (80%)",
        "audience_gender": "Female (91%)",
        "audience_geography": "United States (60%), UK (20%)",
        "bio": "Healthy hair growth protocols, bond maintenance, and low-heat styling."
    },
    {
        "name": "Klaus Vane",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/klaus.minimal",
        "follower_count": 39100,
        "engagement_rate": 3.6,
        "category": "Fashion & Beauty",
        "content_themes": ["Minimalist Wardrobe", "Archival Fashion", "Chelsea Boots"],
        "recent_post_summary": "The anatomy of a black wool overcoat: fit, fabric density, and lapel width.",
        "email": "klaus@vaneagency.de",
        "website": "Not Found",
        "audience_age": "22-36 (75%)",
        "audience_gender": "Male (78%)",
        "audience_geography": "Germany (50%), United States (25%)",
        "bio": "Berlin based. Form follows function. Minimal menswear & design."
    },
    {
        "name": "Giselle Laurent",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/gisellelaurent",
        "follower_count": 82400,
        "engagement_rate": 2.7,
        "category": "Fashion & Beauty",
        "content_themes": ["Luxury Beauty", "Perfume Layering", "Silky Skin"],
        "recent_post_summary": "Layering vanilla amber perfume oils with floral eau de parfum for an intoxicating signature sillage.",
        "email": "giselle.mgmt@laurentpr.fr",
        "website": "https://gisellelaurent.fr",
        "audience_age": "25-42 (72%)",
        "audience_gender": "Female (85%)",
        "audience_geography": "France (35%), United States (35%), UK (18%)",
        "bio": "Art of fragrance and French beauty philosophy. Ambassador & storyteller."
    },
    {
        "name": "Samira Khan",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@samiraskincorrect",
        "follower_count": 44100,
        "engagement_rate": 4.6,
        "category": "Fashion & Beauty",
        "content_themes": ["Dark Circles", "Kojic Acid", "Gentle Peels"],
        "recent_post_summary": "How I faded stubborn genetic dark circles using caffeine serum and hydrating peptides.",
        "email": "collabs.samirakhan@gmail.com",
        "website": "Not Found",
        "audience_age": "18-30 (79%)",
        "audience_gender": "Female (89%)",
        "audience_geography": "United Kingdom (45%), United States (38%)",
        "bio": "Real unfiltered skincare reviews for hyperpigmentation and sensitive skin barriers."
    },
    {
        "name": "Tessa Wright",
        "platform": "YouTube",
        "profile_url": "https://youtube.com/@tessawrightstyle",
        "follower_count": 61500,
        "engagement_rate": 3.9,
        "category": "Fashion & Beauty",
        "content_themes": ["Spring Lookbooks", "Linen Essentials", "Summer Dresses"],
        "recent_post_summary": "15 breathable 100% linen pieces under $100 for effortless warm weather styling.",
        "email": "tessa@tessawrightstyle.com",
        "website": "https://tessawrightstyle.com",
        "audience_age": "24-38 (74%)",
        "audience_gender": "Female (90%)",
        "audience_geography": "Australia (45%), United States (35%)",
        "bio": "Sun-drenched Sydney style. Natural textures, breezy silhouettes, and curated wardrobes."
    },
    {
        "name": "Mateo Silva",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/mateosilvastyle",
        "follower_count": 18200,
        "engagement_rate": 4.4,
        "category": "Fashion & Beauty",
        "content_themes": ["Smart Casual", "Sneaker Pairings", "Men's Jackets"],
        "recent_post_summary": "Styling suede chore jackets for spring weekends with ecru denim and loafers.",
        "email": "collabs@mateosilva.es",
        "website": "Not Found",
        "audience_age": "20-34 (74%)",
        "audience_gender": "Male (82%)",
        "audience_geography": "Spain (40%), United States (32%)",
        "bio": "Madrid based | Elevating casual menswear with clean lines and timeless shades."
    },
    {
        "name": "Isla MacLeod",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@islascleanbeauty",
        "follower_count": 26800,
        "engagement_rate": 5.1,
        "category": "Fashion & Beauty",
        "content_themes": ["Clean Beauty", "Mineral Sunscreen", "Non-Comedogenic"],
        "recent_post_summary": "Ranking non-pore-clogging facial oils for dry acne-prone skin during winter.",
        "email": "isla.cleanbeauty@gmail.com",
        "website": "Not Found",
        "audience_age": "18-28 (78%)",
        "audience_gender": "Female (92%)",
        "audience_geography": "United Kingdom (58%), United States (25%)",
        "bio": "Edinburgh girl sharing ingredient transparency, zero-fragrance skincare, and clean glows."
    },
    {
        "name": "Zion Taylor",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/ziontaylorglow",
        "follower_count": 35400,
        "engagement_rate": 3.7,
        "category": "Fashion & Beauty",
        "content_themes": ["Ceramide Balms", "Glass Lips", "Gentle Retinol"],
        "recent_post_summary": "My evening 4-layer hydration sandwich method for plump morning skin.",
        "email": "ziontaylorglow@outlook.com",
        "website": "Not Found",
        "audience_age": "20-32 (71%)",
        "audience_gender": "Female (86%)",
        "audience_geography": "United States (76%)",
        "bio": "Skincare enthusiast obsessed with deep hydration and calming redness."
    },
    {
        "name": "Nora Lindholm",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/noralindholm",
        "follower_count": 52100,
        "engagement_rate": 3.2,
        "category": "Fashion & Beauty",
        "content_themes": ["Nordic Style", "Knitwear Care", "Monochrome Coats"],
        "recent_post_summary": "Caring for pure cashmere knits and styling them with relaxed tailored wool pants.",
        "email": "nora@lindholmpr.no",
        "website": "https://noralindholm.no",
        "audience_age": "25-40 (70%)",
        "audience_gender": "Female (88%)",
        "audience_geography": "Norway (42%), United States (28%)",
        "bio": "Oslo slow fashion, sustainable woolens, and mindful everyday style."
    },
    {
        "name": "Elijah Banks",
        "platform": "YouTube",
        "profile_url": "https://youtube.com/@elijahbanksskin",
        "follower_count": 48700,
        "engagement_rate": 4.3,
        "category": "Fashion & Beauty",
        "content_themes": ["Salicylic Acid Cleansers", "Oily Skin Prep", "Mattifying Sunscreens"],
        "recent_post_summary": "Top 5 shine-control sunscreens tested under 85-degree humidity with 8-hour blotting tests.",
        "email": "elijahbanks.biz@gmail.com",
        "website": "Not Found",
        "audience_age": "18-30 (72%)",
        "audience_gender": "Male (60%), Female (40%)",
        "audience_geography": "United States (78%)",
        "bio": "Taking control of oily & breakout-prone skin with science and patience."
    },
    {
        "name": "Harper Quinn",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@harperquinnstyle",
        "follower_count": 13900,
        "engagement_rate": 6.3,
        "category": "Fashion & Beauty",
        "content_themes": ["Vintage Leather", "Boho Chic", "Summer Festival Fits"],
        "recent_post_summary": "Thrifting vintage 90s leather jackets and restoring them with saddle leather conditioner.",
        "email": "harper@quinncreative.com",
        "website": "Not Found",
        "audience_age": "17-25 (83%)",
        "audience_gender": "Female (89%)",
        "audience_geography": "United States (79%)",
        "bio": "Vintage thrifter, 90s nostalgia fashion, and DIY shoe revamps."
    },
    {
        "name": "Amina Diop",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/aminadiopglow",
        "follower_count": 42300,
        "engagement_rate": 4.1,
        "category": "Fashion & Beauty",
        "content_themes": ["Melanin Skin Glow", "Body Oils", "Barrier Repair"],
        "recent_post_summary": "Shimmering dry body oils that deeply hydrate without staining light silk clothing.",
        "email": "amina@diopagency.com",
        "website": "https://aminadiop.com",
        "audience_age": "20-35 (77%)",
        "audience_gender": "Female (93%)",
        "audience_geography": "United States (54%), France (25%)",
        "bio": "Gleaming skin from head to toe. Celebrating rich skin tones and holistic moisture."
    },
    {
        "name": "Ben Carter",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@bencarterstyle",
        "follower_count": 25100,
        "engagement_rate": 4.0,
        "category": "Fashion & Beauty",
        "content_themes": ["Workwear Jackets", "Loafer Styling", "Seasonal Basics"],
        "recent_post_summary": "3 casual spring jackets that look 10x more expensive than they actually are.",
        "email": "bencarter.partnerships@gmail.com",
        "website": "Not Found",
        "audience_age": "20-30 (73%)",
        "audience_gender": "Male (79%)",
        "audience_geography": "United States (70%), Canada (18%)",
        "bio": "Helping young professionals build versatile capsule wardrobes with zero stress."
    },
    {
        "name": "Ruby Thorne",
        "platform": "YouTube",
        "profile_url": "https://youtube.com/@rubythornemakeup",
        "follower_count": 66200,
        "engagement_rate": 3.4,
        "category": "Fashion & Beauty",
        "content_themes": ["Gothic Glam", "Vampy Lipsticks", "Smokey Eyes"],
        "recent_post_summary": "The ultimate guide to smudge-proof dramatic black winged eyeliner for hooded eyes.",
        "email": "collabs@rubythorne.co.uk",
        "website": "https://rubythorne.co.uk",
        "audience_age": "18-29 (75%)",
        "audience_gender": "Female (88%)",
        "audience_geography": "United Kingdom (52%), United States (30%)",
        "bio": "Edgy glam, dramatic lashes, and deep berry lips. Cruelty free makeup tests."
    },
    {
        "name": "Chloe Chen-Wu",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/chloechenbeauty",
        "follower_count": 31400,
        "engagement_rate": 4.5,
        "category": "Fashion & Beauty",
        "content_themes": ["Korean Sunscreens", "Cica Creams", "Morning Routines"],
        "recent_post_summary": "Centella asiatica (Cica) soothing gel comparison for calm, red-free skin in humid weather.",
        "email": "Not Found",
        "website": "https://chloechen.link",
        "audience_age": "19-31 (74%)",
        "audience_gender": "Female (89%)",
        "audience_geography": "United States (62%), Canada (20%)",
        "bio": "K-Beauty routine lover | Soothing sensitive skin | DM for PR inquires"
    },
    {
        "name": "Julian Mercer",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/julianmercer",
        "follower_count": 59300,
        "engagement_rate": 3.1,
        "category": "Fashion & Beauty",
        "content_themes": ["Old Money Aesthetic", "Polo Shirts", "Tailored Linen"],
        "recent_post_summary": "Summer resort wear: styling breezy linen shirts and pleated shorts with woven loafers.",
        "email": "julian.mercer.collab@gmail.com",
        "website": "Not Found",
        "audience_age": "22-38 (70%)",
        "audience_gender": "Male (75%)",
        "audience_geography": "United States (55%), UK (25%)",
        "bio": "Classic aesthetic menswear. Heritage fabrics, tailored fits, and timeless elegance."
    },
    {
        "name": "Zara Al-Hassan",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@zaraskinsecrets",
        "follower_count": 88400,
        "engagement_rate": 3.8,
        "category": "Fashion & Beauty",
        "content_themes": ["Hydrating Mists", "Gua Sha Routine", "Glow Serums"],
        "recent_post_summary": "5-minute morning lymphatic drainage gua sha routine with rosehip seed oil.",
        "email": "contact@zaraskinsecrets.com",
        "website": "https://zaraskinsecrets.com",
        "audience_age": "20-34 (76%)",
        "audience_gender": "Female (91%)",
        "audience_geography": "UAE (40%), United States (30%), UK (20%)",
        "bio": "Holistic skin sculpting and radiant botanical formulas for healthy glowing complexion."
    },
    {
        "name": "Kelsey Adams",
        "platform": "YouTube",
        "profile_url": "https://youtube.com/@kelseyadamshair",
        "follower_count": 37900,
        "engagement_rate": 4.7,
        "category": "Fashion & Beauty",
        "content_themes": ["Silk Pillowcases", "Split End Care", "Blowout Tutorials"],
        "recent_post_summary": "90s salon bouncy blowout tutorial at home using round ceramic brushes and velcro rollers.",
        "email": "kelseyadams.partnerships@gmail.com",
        "website": "Not Found",
        "audience_age": "18-32 (79%)",
        "audience_gender": "Female (95%)",
        "audience_geography": "United States (82%)",
        "bio": "Licensed cosmetologist sharing salon-grade blowouts and deep conditioning secrets."
    },
    {
        "name": "Leo Fontaine",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/leofontainestyle",
        "follower_count": 17400,
        "engagement_rate": 4.9,
        "category": "Fashion & Beauty",
        "content_themes": ["Parisian Menswear", "Silk Scarves", "Trench Coats"],
        "recent_post_summary": "The art of draping a silk pocket square and matching classic trench coat belt knots.",
        "email": "leo@fontaineparis.com",
        "website": "https://leofontaine.fr",
        "audience_age": "22-35 (72%)",
        "audience_gender": "Male (77%)",
        "audience_geography": "France (45%), United States (28%)",
        "bio": "Modern Parisian nonchalance. Tailoring, vintage timepieces, and understated chic."
    },
    {
        "name": "Serena Joy",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@serenaglowroutine",
        "follower_count": 41800,
        "engagement_rate": 4.2,
        "category": "Fashion & Beauty",
        "content_themes": ["Lip Peptides", "Squalane Oils", "Evening GRWM"],
        "recent_post_summary": "How plant-derived squalane transformed my dry combination skin barrier in 14 days.",
        "email": "serenajoy.collabs@gmail.com",
        "website": "Not Found",
        "audience_age": "18-28 (80%)",
        "audience_gender": "Female (90%)",
        "audience_geography": "United States (74%), UK (16%)",
        "bio": "Skincare enthusiast tracking ingredient effects. Healthy skin over perfect skin 🤍"
    },
    {
        "name": "Emma Watson-Cole",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/emmacolebeauty",
        "follower_count": 21300,
        "engagement_rate": 3.7,
        "category": "Fashion & Beauty",
        "content_themes": ["Cruelty-Free Lashes", "Dewy Cheek Tints", "Everyday Routine"],
        "recent_post_summary": "My 3-step lip and cheek monochromatic tint look for hot sunny days.",
        "email": "emma@colecreative.co.uk",
        "website": "Not Found",
        "audience_age": "19-33 (75%)",
        "audience_gender": "Female (91%)",
        "audience_geography": "United Kingdom (65%), United States (20%)",
        "bio": "London based beauty creator | Natural skin finishes & gentle formulas"
    },
    {
        "name": "Gabriel Santos",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@gabrielsantosfits",
        "follower_count": 48100,
        "engagement_rate": 3.6,
        "category": "Fashion & Beauty",
        "content_themes": ["Oversized Fits", "Cargo Pants", "Chunky Loafers"],
        "recent_post_summary": "How to style chunky black loafers without looking like school uniform trousers.",
        "email": "gabriel.collab@gmail.com",
        "website": "Not Found",
        "audience_age": "18-26 (84%)",
        "audience_gender": "Male (72%)",
        "audience_geography": "United States (60%), Brazil (25%)",
        "bio": "Streetwear proportions & footwear rotation. Keep it comfortable and sharp."
    },
    {
        "name": "Victoria Stone",
        "platform": "YouTube",
        "profile_url": "https://youtube.com/@victoriastoneglow",
        "follower_count": 55900,
        "engagement_rate": 4.1,
        "category": "Fashion & Beauty",
        "content_themes": ["Vitamin C Serums", "Under-Eye Creams", "Anti-Pollution Skincare"],
        "recent_post_summary": "Stabilized L-ascorbic acid vs THD ascorbate: which vitamin C actually brightens faster?",
        "email": "partnerships@victoriastone.com",
        "website": "https://victoriastone.com",
        "audience_age": "24-42 (71%)",
        "audience_gender": "Female (88%)",
        "audience_geography": "United States (67%), Canada (18%)",
        "bio": "Deep research into active skincare ingredients. Real microscope comparisons & tests."
    },
    {
        "name": "Felix Thorne",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/felixthorne_crypto",
        "follower_count": 62000,
        "engagement_rate": 2.1,
        "category": "Crypto & Web3",
        "content_themes": ["Bitcoin Trading", "Altcoin Signals", "NFT Drops"],
        "recent_post_summary": "Why the Bitcoin halving cycle will trigger an exponential bull market for altcoins.",
        "email": "felix@cryptoinvestor.xyz",
        "website": "https://cryptoinvestor.xyz",
        "audience_age": "18-35 (85%)",
        "audience_gender": "Male (88%)",
        "audience_geography": "United States (50%)",
        "bio": "Daily crypto charts, web3 alpha, and trading signals. Not financial advice."
    },
    {
        "name": "Bella Thorne-Brooks",
        "platform": "TikTok",
        "profile_url": "https://tiktok.com/@bellafashiontiny",
        "follower_count": 3200,
        "engagement_rate": 7.4,
        "category": "Fashion & Beauty",
        "content_themes": ["Thrifting Hauls", "Y2K Baby Tees"],
        "recent_post_summary": "Thrifting baby tees at local flea market for $3 each.",
        "email": "bella.tiny@gmail.com",
        "website": "Not Found",
        "audience_age": "16-22 (90%)",
        "audience_gender": "Female (95%)",
        "audience_geography": "United States (85%)",
        "bio": "Just started sharing my thrifting addiction! 💖"
    },
    {
        "name": "Cassandra Blake",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/cassandrablake_mega",
        "follower_count": 285000,
        "engagement_rate": 1.4,
        "category": "Fashion & Beauty",
        "content_themes": ["Red Carpet Glam", "Celebrity Hauls", "Fashion Week Front Row"],
        "recent_post_summary": "Front row highlights from Milan Fashion Week autumn collection.",
        "email": "mgmt@cassandrablake.com",
        "website": "https://cassandrablake.com",
        "audience_age": "18-35 (75%)",
        "audience_gender": "Female (82%)",
        "audience_geography": "United States (60%)",
        "bio": "International model & brand ambassador. Business inquiries via agency only."
    },
    {
        "name": "Olivia Vance",
        "platform": "Instagram",
        "profile_url": "https://instagram.com/oliviavance_sleepy",
        "follower_count": 18500,
        "engagement_rate": 0.8,
        "category": "Fashion & Beauty",
        "content_themes": ["Reposted Outfits", "Giveaways", "Aesthetic Photos"],
        "recent_post_summary": "Weekly neutral aesthetic photo dump with inspirational quotes.",
        "email": "olivia.sleepy@gmail.com",
        "website": "Not Found",
        "audience_age": "20-30 (60%)",
        "audience_gender": "Female (80%)",
        "audience_geography": "United States (50%)",
        "bio": "Giveaways only. DM to be featured. F4F daily."
    },
    {
        "name": "TechGuru Sam",
        "platform": "YouTube",
        "profile_url": "https://youtube.com/@techgurusampc",
        "follower_count": 48000,
        "engagement_rate": 4.1,
        "category": "Technology",
        "content_themes": ["GPU Benchmarks", "Custom Watercooling", "Gaming Keyboards"],
        "recent_post_summary": "Testing RTX 4080 thermal throttling in compact mini-ITX cases.",
        "email": "sam@techgurus.io",
        "website": "https://techgurus.io",
        "audience_age": "18-34 (88%)",
        "audience_gender": "Male (92%)",
        "audience_geography": "United States (65%)",
        "bio": "PC hardware overclocking, custom loops, and clean desk setups."
    }
]

def get_initial_influencers() -> List[Dict[str, Any]]:
    return [parse_creator_profile(p) for p in DEFAULT_DISCOVERED_DATA]

def save_raw_influencers(influencers: List[Dict[str, Any]], filepath: Path = RAW_DATA_PATH) -> Path:
    filepath.parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(influencers, f, indent=2, ensure_ascii=False)
    return filepath

def run_discovery() -> List[Dict[str, Any]]:
    influencers = get_initial_influencers()
    save_raw_influencers(influencers, RAW_DATA_PATH)
    return influencers
